Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2021-05, with the labels that each got.

#586 [4.x.x] Error to export table with expandable row
  ontimize/components/table/extensions/header/table-menu/o-table-menu.component.ts
Labels: bug

#587 [4.x.x] Fix to initial sort on table not working with static data
  CHANGELOG.md
  ontimize/components/service.utils.ts
  ontimize/components/table/extensions/sort/o-mat-sort.ts
  ontimize/components/table/o-table.component.ts
Labels: bug, fixed

#584 [4.x.x] Set event as optional in toggleRowExpandable
  ontimize/components/table/o-table.component.ts
Labels: enhancement, fixed

#588 [8.x.x] Fix to initial sort on table not working with static data
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: bug, fixed

#585 [8.x.x] Set event as optional in toggleRowExpandable
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: enhancement, fixed

#570 [8.x.x] Icon Combo renderer
  projects/ontimize-web-ngx/src/lib/components/input/combo/combo-renderer/combo-renderer.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/combo-renderer/icon/o-combo-renderer-icon.component.html
  projects/ontimize-web-ngx/src/lib/components/input/combo/combo-renderer/icon/o-combo-renderer-icon.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/combo-renderer/index.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/combo-renderer/o-combo-renderer.class.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.html
  projects/ontimize-web-ngx/src/lib/pipes/index.ts
  projects/ontimize-web-ngx/src/lib/pipes/o-icon.pipe.ts
  projects/ontimize-web-ngx/src/lib/services/icon.service.ts
  projects/ontimize-web-ngx/src/lib/services/index.ts
  projects/ontimize-web-ngx/src/lib/shared/shared.module.ts
Labels: enhancement, fixed

#593 [8.x.x] Try catch exception on setItem of localStorage
  projects/ontimize-web-ngx/src/lib/services/local-storage.service.ts
  projects/ontimize-web-ngx/src/lib/services/login-storage.service.ts
  projects/ontimize-web-ngx/src/lib/services/translate/o-translate.service.ts
Labels: bug

#604 [8.x.x] Show clear button when combo is not empty
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.ts
Labels: bug

#617 [8.2.5] o-list-picker displays required error with valid initial data
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.ts
Labels: bug

#611 [8.x.x] Quickfilter filter-case-sensitive error in console
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: bug, fixed

#618 [8.2.5] Fixing o-list-picker custom renderers
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/input/listpicker/listpicker-renderer/o-list-picker-renderer.class.ts
  projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker-dialog.component.html
  projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker-dialog.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.html
  projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.ts
Labels: bug
