Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2021-07, with the labels that each got.

#662 Adding build CI workflows
  .github/workflows/build-ci.yml
Labels: enhancement

#661 [8.x.x] Validators in table cell editors and insertable row
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/input/text-input/o-text-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/o-form-data-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/date/o-table-cell-editor-date.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/email/o-table-cell-editor-email.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/integer/o-table-cell-editor-integer.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/o-base-table-cell-editor.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/real/o-table-cell-editor-real.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/text/o-table-cell-editor-text.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/text/o-table-cell-editor-text.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/time/o-table-cell-editor-time.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/o-table-column.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-insertable-row/o-table-insertable-row.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/interfaces/o-table-column.interface.ts
Labels: enhancement

#669 [8.x.x] o-table: Cannot read property 'onChange' of undefined in oTableExpandedFooter directive
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/expanded/o-table-expanded-footer.directive.ts
Labels: bug, table

#671 [8.x.x] Protect code on resolve validators for row-insertable
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-insertable-row/o-table-insertable-row.component.ts
Labels: bug

#673 [8.x.x] Rename oFormValue to o-form-value for Github Action
  projects/ontimize-web-ngx/src/lib/components/form/index.ts
  projects/ontimize-web-ngx/src/lib/components/form/o-form-value.ts
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
  projects/ontimize-web-ngx/src/lib/components/image/o-image.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/date-input/o-date-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/hour-input/o-hour-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/integer-input/o-integer-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/o-boolean-form-data-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/input/radio/o-radio.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/slide-toggle/o-slide-toggle.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/time-input/o-time-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/o-form-data-component.class.ts
  projects/ontimize-web-ngx/src/lib/util/service.utils.ts
Labels: bug

#676 New method destroy in o-table-datasource
  projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/interfaces/o-table-datasource.interface.ts
Labels: bug

#685 [8.x.x] Fixed not refresh events in datasource when group and ungroup columns
  projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/o-table-strategy.service.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: bug

#688 [8.x.x] Set fixed-header='yes' by default
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: bug

#698 [8.x.x] Function setFieldValues not working fine on o-combo and o-list-picker
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/o-form-service-component.class.ts
Labels: bug
