Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2022-11, with the labels that each got.

#1077 Fixed NodeJS 12 warning on actions
  .github/workflows/build-ci.yml
  .github/workflows/build-manually.yml
  .github/workflows/build-release.yml
  .github/workflows/release-preview.yml
  .github/workflows/sonar.yml
Labels: fixed

#1072 [8.x.x] Charts on demand
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/i18n/i18n.ts
  projects/ontimize-web-ngx/src/lib/interfaces/chart-on-demand.interface.ts
  projects/ontimize-web-ngx/src/lib/interfaces/index.ts
  projects/ontimize-web-ngx/src/lib/services/factories.ts
Labels: enhancement

#1001 [8.x.x] Load/Save/Clear filter builder configuration
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/filter-builder/filter-builder-menu/filter-builder-menu.component.html
  projects/ontimize-web-ngx/src/lib/components/filter-builder/filter-builder-menu/filter-builder-menu.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/filter-builder/filter-builder-menu/filter-builder-menu.component.ts
  projects/ontimize-web-ngx/src/lib/components/filter-builder/o-filter-builder.component.ts
  projects/ontimize-web-ngx/src/lib/components/filter-builder/o-filter-builder.module.ts
  projects/ontimize-web-ngx/src/lib/components/input/phone-input/o-phone-input.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/input/test/input-test-utils.ts
  projects/ontimize-web-ngx/src/lib/components/input/test/test-utils.ts
  projects/ontimize-web-ngx/src/lib/components/input/text-input/o-text-input.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/index.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/load-filter/o-table-load-filter-dialog.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/o-table-dialog-components.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/store-filter/o-table-store-filter-dialog.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/i18n/i18n.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-component-state.class.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-component-state.service.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-filter-builder-component-state.class.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-filter-builder-component-state.service.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-grid-component-state.class.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-list-component-state.class.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-table-component-state.class.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-table-component-state.service.ts
  projects/ontimize-web-ngx/src/lib/shared/components/filter/load-filter/o-load-filter-dialog.component.html
  projects/ontimize-web-ngx/src/lib/shared/components/filter/load-filter/o-load-filter-dialog.component.ts
  projects/ontimize-web-ngx/src/lib/shared/components/filter/store-filter/o-store-filter-dialog.component.html
  projects/ontimize-web-ngx/src/lib/shared/components/filter/store-filter/o-store-filter-dialog.component.ts
  projects/ontimize-web-ngx/src/lib/shared/shared.module.ts
  projects/ontimize-web-ngx/src/lib/types/index.ts
  projects/ontimize-web-ngx/src/lib/types/o-filter-builder-values.type.ts
  projects/ontimize-web-ngx/src/lib/types/o-filter-definition.type.ts
  projects/ontimize-web-ngx/src/lib/types/table/o-table-filter-status.type.ts
Labels: enhancement

#1080 [8.8.1] The quick filter styles of the list or grid components are not displayed correctly
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.scss
Labels: bug

#1082 `oFilterBuilderClear` directive not clearing the value of the `o-combo` multiple
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/filter-builder/o-filter-builder.component.ts
Labels: bug

#1088 [8.x.x] Modified chart-on-demand parameters
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts
  projects/ontimize-web-ngx/src/lib/interfaces/chart-on-demand.interface.ts
Labels: enhancement

#1095 Hotfix 8.8.1
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/button-toggle/o-button-toggle.component.html
  projects/ontimize-web-ngx/src/lib/components/filter-builder/o-filter-builder.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.scss
  projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: release
