Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2023-07, with the labels that each got.

#1243 o-integer: removing unnecesary firefox workaround
  projects/ontimize-web-ngx/src/lib/components/input/integer-input/o-integer-input.component.ts
Labels: bug

#1248 [Bugfix] Filter in table with row grouping
  projects/ontimize-web-ngx/src/lib/services/local-storage.service.ts
  projects/ontimize-web-ngx/src/lib/util/util.ts
Labels: bug

#1252 [Bugfix] solved localstorage not saving correctly
  projects/ontimize-web-ngx/src/lib/services/local-storage.service.ts
Labels: bug

#1255 Release 8.13.0
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.scss
  projects/ontimize-web-ngx/src/lib/components/input/integer-input/o-integer-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-renderer/service/o-table-cell-renderer-service.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-column-resizer/o-table-column-resizer.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header-column-filter-icon/o-table-header-column-filter-icon.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header/o-table-header.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header/o-table-header.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header/o-table-header.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/sort/sort-header.scss
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/services/local-storage.service.ts
  projects/ontimize-web-ngx/src/lib/types/table/o-column-display.type.ts
  projects/ontimize-web-ngx/src/lib/types/table/o-table-global-config.type.ts
  projects/ontimize-web-ngx/src/lib/util/util.ts
Labels: release

#1265 Modified getColumnFilter visibility
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: enhancement

#1271 Release 8.14.0
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/form/guards/o-form-can-deactivate.guard.ts
  projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form-confirm-exit.service.ts
  projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/integer-input/o-integer-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/o-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/o-form-data-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/date/o-table-cell-editor-date.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/email/o-table-cell-editor-email.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/integer/o-table-cell-editor-integer.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/integer/o-table-cell-editor-integer.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/o-base-table-cell-editor.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/real/o-table-cell-editor-real.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/real/o-table-cell-editor-real.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/text/o-table-cell-editor-text.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/time/o-table-cell-editor-time.component.html
  projects/ontimize-web-ngx/src/lib/components/table/column/o-table-column.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/o-table-base-dialog.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/directives/o-mat-error.directive.ts
  projects/ontimize-web-ngx/src/lib/interfaces/o-form-layout-manager-mode.interface.ts
  projects/ontimize-web-ngx/src/lib/interfaces/o-table-column.interface.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
  projects/ontimize-web-ngx/src/lib/shared/components/validation/o-validator.component.ts
  projects/ontimize-web-ngx/src/lib/util/errors.ts
  projects/ontimize-web-ngx/src/lib/validators/o-validators.ts
Labels: release
