Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2023-11, with the labels that each got.

#1379 [15.x.x] Modified report-on-demand styles
  projects/ontimize-web-ngx/src/lib/theming/addons/report-on-demand.scss
Labels: enhancement, v15

#1381 Release 15.0.0-beta.3
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/ontimize.scss
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss
  projects/ontimize-web-ngx/src/lib/components/dual-list-selector/o-dual-list-selector-theme.scss
  projects/ontimize-web-ngx/src/lib/components/dual-list-selector/o-dual-list-selector.component.html
  projects/ontimize-web-ngx/src/lib/components/dual-list-selector/o-dual-list-selector.component.scss
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.scss
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.scss
  projects/ontimize-web-ngx/src/lib/components/input/phone-input/o-phone-input.component.html
  projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.scss
  projects/ontimize-web-ngx/src/lib/components/list/list-item/o-list-item.component.scss
  projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html
  projects/ontimize-web-ngx/src/lib/components/list/o-list.component.scss
  projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts
  projects/ontimize-web-ngx/src/lib/components/list/renderers/card-image/o-list-item-card-image.component.html
  projects/ontimize-web-ngx/src/lib/components/list/renderers/card-image/o-list-item-card-image.component.scss
  projects/ontimize-web-ngx/src/lib/components/list/renderers/card/o-list-item-card.component.html
  projects/ontimize-web-ngx/src/lib/components/list/renderers/card/o-list-item-card.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/apply-configuration/o-table-apply-configuration-dialog.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/store-configuration/o-table-store-configuration-dialog.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/store-configuration/o-table-store-configuration-dialog.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/visible-columns/o-table-visible-columns-dialog.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/visible-columns/o-table-visible-columns-dialog.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/components/theming/app-global.theme.scss
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.scss
  projects/ontimize-web-ngx/src/lib/shared/components/filter/load-filter/o-load-filter-dialog.component.html
  projects/ontimize-web-ngx/src/lib/theming/addons/report-on-demand.scss
  projects/ontimize-web-ngx/src/lib/theming/ontimize-style-v8.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/density.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/o-form-field-style.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/o-table-style.scss
Labels: release

#1384 Hotfix 8.14.4
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.html
  projects/ontimize-web-ngx/src/lib/i18n/i18n.ts
Labels: release

#1390 [15.x.x] Created currency util
  package-lock.json
  projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.ts
  projects/ontimize-web-ngx/src/lib/util/currencyUtil.ts
  projects/ontimize-web-ngx/src/lib/util/index.ts
Labels: bug, v15

#1397 [15.x.x] Removed the common inputs with OFormDataComponent
  projects/ontimize-web-ngx/src/lib/components/input/file-input/o-file-input.component.ts
Labels: v15

#1398 [15.x.x ]Added change in emitOnValueChange to reset values
  projects/ontimize-web-ngx/src/lib/components/input/o-form-service-component.class.ts
Labels: bug, v15
