Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2023-10, with the labels that each got.

#1290 Fixed action columns bug
  .github/workflows/build-release.yml
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: bug

#1291 [8.14.1] CHANGELOG
  CHANGELOG.md
Labels: enhancement

#1289 Hotfix 8.14.1
  .github/workflows/build-release.yml
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: release

#1294 Release 15.0.0-beta.1
  .github/workflows/build-manually.yml
  .github/workflows/build-release.yml
  .github/workflows/deploy-snapshot-nexus.yml
  .github/workflows/release-preview.yml
  .github/workflows/sonar.yml
  CHANGELOG.md
  gulpfile.js
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/card-menu-item/o-card-menu-item.component.theme.scss
  projects/ontimize-web-ngx/src/lib/components/container/o-container-theme.scss
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/styles/o-table-typography.theme.scss
  projects/ontimize-web-ngx/src/lib/components/theming/app-global.theme.scss
  projects/ontimize-web-ngx/src/lib/services/appearance.service.ts
  projects/ontimize-web-ngx/src/lib/shared/material/o-material.theme.scss
  projects/ontimize-web-ngx/src/lib/theming/addons/charts-on-demand.scss
  projects/ontimize-web-ngx/src/lib/theming/addons/report-on-demand.scss
  projects/ontimize-web-ngx/src/lib/theming/ontimize-style-v8.scss
  projects/ontimize-web-ngx/src/lib/theming/ontimize-style.scss
  projects/ontimize-web-ngx/src/lib/theming/ontimize-theme-flat.scss
  projects/ontimize-web-ngx/src/lib/theming/ontimize-theme-lite.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/default/typography/ontimize.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/flat/variables.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/layout.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/lite/form-field/o-form-field-theme.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/lite/layout.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/lite/paginator.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/containers.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/o-form-field-style.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/o-table-style.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/variables.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize/typography-ontimize.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize/variables.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/paginator.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/fashion.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/implatform-fashion-default-theme.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/mat-deeppurple-amber.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/mat-indigo-pink.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/mat-pink-bluegrey.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/mat-purple-green.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/ontimize-black-yellow.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/ontimize-blue.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/ontimize.scss
  projects/ontimize-web-ngx/src/lib/theming/typography/o-table-typography.scss
  projects/ontimize-web-ngx/src/lib/theming/typography/ontimize.scss
Labels: release

#1311 [15.x.x] o-error-dialog: fixed bug that prevents opening the dialog
  projects/ontimize-web-ngx/src/lib/services/o-error-dialog-manager.service.ts
Labels: bug

#1303 Hotfix 8.14.2
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/services/translate/o-translate.service.ts
  projects/ontimize-web-ngx/src/lib/util/util.ts
Labels: release

#1321 o-table: fixed not showing any message that there are no results
  projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
Labels: bug

#1320 Hotfix 8.14.3
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
Labels: release

#1340 Release 15.0.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss
  projects/ontimize-web-ngx/src/lib/components/button-toggle/o-button-toggle-group/o-button-toggle-group.component.ts
  projects/ontimize-web-ngx/src/lib/components/card-menu-item/o-card-menu-item.component.ts
  projects/ontimize-web-ngx/src/lib/components/form-container/o-form-container.component.ts
  projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts
  projects/ontimize-web-ngx/src/lib/components/index.ts
  projects/ontimize-web-ngx/src/lib/components/input/input-theme.scss
  projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/calculated/o-table-column-calculated.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/o-table-column.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-insertable-row/o-table-insertable-row.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/components/theming/app-global.theme.scss
  projects/ontimize-web-ngx/src/lib/components/user-info/index.ts
  projects/ontimize-web-ngx/src/lib/components/user-info/o-user-info.module.ts
  projects/ontimize-web-ngx/src/lib/interfaces/o-table-column.interface.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.html
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/options/o-form-layout-dialog-options.directive.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
  projects/ontimize-web-ngx/src/lib/services/o-error-dialog-manager.service.ts
  projects/ontimize-web-ngx/src/lib/services/translate/o-translate.service.ts
  projects/ontimize-web-ngx/src/lib/theming/ontimize-style-v8.scss
  projects/ontimize-web-ngx/src/lib/theming/ontimize-style.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/o-form-field-style.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/variables.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/ontimize-blue.scss
  projects/ontimize-web-ngx/src/lib/util/util.ts
Labels: release
