Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2024-06, with the labels that each got.

#1613 [8.14.15] Solved bug with table permissions
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: bug

#1617 [o-tree] Added permissions to o-tree
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.component.html
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.component.ts
  projects/ontimize-web-ngx/src/lib/services/permissions/permissions.service.ts
  projects/ontimize-web-ngx/src/lib/types/o-tree-permissions.type.ts
Labels: enhancement

#1620 Hotfix 8.14.16
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/services/app-menu.service.ts
  projects/ontimize-web-ngx/src/lib/util/util.ts
Labels: release
