Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2024-02, with the labels that each got.

#1459 Hotfix 8.14.8
  .github/workflows/release-preview.yml
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form-navigation.component.ts
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.theme.scss
  projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
  projects/ontimize-web-ngx/src/lib/i18n/i18n.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.ts
  projects/ontimize-web-ngx/src/lib/util/util.ts
Labels: release

#1482 [15.x.x] [o-grid] Modified insert button translation
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html
Labels: bug

#1483 [8.14.9] [o-grid] Modified insert button translation
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html
Labels: bug

#1485 [8.14.9] [o-table] Added disable-page-size-calculation input in o-table
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: enhancement

#1490 Sync 8.14.9 to 15.x.x
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form-navigation.component.ts
  projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: enhancement

#1497 Release 15.0.0
  .github/workflows/release-preview.yml
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/ng-package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form-navigation.component.ts
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.module.ts
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.theme.scss
  projects/ontimize-web-ngx/src/lib/components/grid/skeketon/o-grid-skeleton/o-grid-skeleton.component.html
  projects/ontimize-web-ngx/src/lib/components/grid/skeketon/o-grid-skeleton/o-grid-skeleton.component.scss
  projects/ontimize-web-ngx/src/lib/components/grid/skeketon/o-grid-skeleton/o-grid-skeleton.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/grid/skeketon/o-grid-skeleton/o-grid-skeleton.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input-theme.scss
  projects/ontimize-web-ngx/src/lib/components/input/file-input/o-file-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/list/o-list-theme.scss
  projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html
  projects/ontimize-web-ngx/src/lib/components/list/o-list.component.scss
  projects/ontimize-web-ngx/src/lib/components/list/o-list.module.ts
  projects/ontimize-web-ngx/src/lib/components/list/skeleton/o-list-skeleton/o-list-skeleton.component.html
  projects/ontimize-web-ngx/src/lib/components/list/skeleton/o-list-skeleton/o-list-skeleton.component.scss
  projects/ontimize-web-ngx/src/lib/components/list/skeleton/o-list-skeleton/o-list-skeleton.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/list/skeleton/o-list-skeleton/o-list-skeleton.component.ts
  projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/o-skeleton.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/skeleton/o-table-skeleton/o-table-skeleton.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/skeleton/o-table-skeleton/o-table-skeleton.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/skeleton/o-table-skeleton/o-table-skeleton.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/skeleton/o-table-skeleton/o-table-skeleton.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.module.ts
  projects/ontimize-web-ngx/src/lib/components/table/styles/o-table-theme.scss
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup-theme.scss
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.scss
  projects/ontimize-web-ngx/src/lib/theming/ontimize-style.scss
  projects/ontimize-web-ngx/src/lib/util/util.ts
Labels: release

#1505 Hotfix 15.0.1
  CHANGELOG.md
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/grid/index.ts
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.module.ts
  projects/ontimize-web-ngx/src/lib/components/grid/skeketon/o-grid-skeleton.component.html
  projects/ontimize-web-ngx/src/lib/components/grid/skeketon/o-grid-skeleton.component.scss
  projects/ontimize-web-ngx/src/lib/components/grid/skeketon/o-grid-skeleton.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/grid/skeketon/o-grid-skeleton.component.ts
  projects/ontimize-web-ngx/src/lib/components/index.ts
  projects/ontimize-web-ngx/src/lib/components/list/index.ts
  projects/ontimize-web-ngx/src/lib/components/list/o-list.module.ts
  projects/ontimize-web-ngx/src/lib/components/list/skeleton/o-list-skeleton.component.html
  projects/ontimize-web-ngx/src/lib/components/list/skeleton/o-list-skeleton.component.scss
  projects/ontimize-web-ngx/src/lib/components/list/skeleton/o-list-skeleton.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/list/skeleton/o-list-skeleton.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/index.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/skeleton/o-table-skeleton.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/skeleton/o-table-skeleton.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/skeleton/o-table-skeleton.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/skeleton/o-table-skeleton.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/sort/o-mat-sort.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.module.ts
Labels: release
