Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2024-04, with the labels that each got.

#1544 [8.14.10] Fixed bug that caused the width of the columns to not adjust properly on a tablet
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-column-resizer/o-table-column-resizer.component.ts
Labels: bug

#1541 Hotfix 8.14.10
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/menu-group/o-app-sidenav-menu-group.component.html
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/menu-item/o-app-sidenav-menu-item.component.html
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/layout.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/typography.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/variables.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-column-resizer/o-table-column-resizer.component.ts
  projects/ontimize-web-ngx/src/lib/interfaces/app-menu.interface.ts
Labels: release

#1547 [15.x.x] Sync release 8.14.10 to 15.x.x
  CHANGELOG.md
  package-lock.json
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/menu-group/o-app-sidenav-menu-group.component.html
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/menu-item/o-app-sidenav-menu-item.component.html
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/layout.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/typography.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/variables.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-column-resizer/o-table-column-resizer.component.ts
  projects/ontimize-web-ngx/src/lib/interfaces/app-menu.interface.ts
Labels: enhancement

#1551 [8.14.11] [o-form] Initialized header actions
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
Labels: bug

#1552 [8.14.11] [o-daterange-input] Added dark mode
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input-theme.scss
Labels: enhancement

#1553 [8.14.11] CHANGELOG
  CHANGELOG.md
Labels: enhancement

#1549 Hotfix 8.14.11
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input-theme.scss
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.html
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.ts
Labels: release

#1555 Hotfix 8.14.12
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Labels: release

#1561 Hotfix 8.14.13
  .github/workflows/build-ci.yml
  .github/workflows/build-manually.yml
  .github/workflows/build-release.yml
  .github/workflows/deploy-snapshot-nexus.yml
  .github/workflows/prepare-release.yml
  .github/workflows/sonar.yml
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts
  projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts
  projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts
Labels: release

#1571 [15.0.4] Added permissions to o-card-menu-layout
  projects/ontimize-web-ngx/src/lib/layouts/card-menu-layout/o-card-menu-layout.component.ts
Labels: enhancement

#1572 Sync hotfixes to 15.0.4
  .github/workflows/build-release.yml
  CHANGELOG.md
  package-lock.json
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/menu-group/o-app-sidenav-menu-group.component.html
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/menu-item/o-app-sidenav-menu-item.component.html
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input-theme.scss
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.html
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.ts
  projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts
  projects/ontimize-web-ngx/src/lib/components/material/styles/layout.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/typography.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/variables.scss
  projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-column-resizer/o-table-column-resizer.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/interfaces/app-menu.interface.ts
Labels: enhancement

#1575 [15.0.4] Solved bug with exportation in non-pageable tables
  projects/ontimize-web-ngx/src/lib/services/ontimize-export-data-base-provider.service.ts
Labels: bug

#1579 [15.0.4] Added styles to o-tree
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.component.html
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.component.ts
  projects/ontimize-web-ngx/src/lib/theming/ontimize-style.scss
Labels: enhancement

#1581 [15.0.4] Modified imports
  projects/ontimize-web-ngx/src/lib/services/ontimize-export-data-base-provider.service.ts
Labels: bug

#1580 [15.0.4] Added dark theme to o-hour
  projects/ontimize-web-ngx/src/lib/components/input/hour-input/o-hour-input-theme.scss
Labels: bug

#1573 CHANGELOG 15.0.4
  CHANGELOG.md
Labels: enhancement

#1570 Hotfix 15.0.4
  .github/workflows/build-release.yml
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/menu-group/o-app-sidenav-menu-group.component.html
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/menu-item/o-app-sidenav-menu-item.component.html
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input-theme.scss
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.html
  projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/hour-input/o-hour-input-theme.scss
  projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts
  projects/ontimize-web-ngx/src/lib/components/material/styles/layout.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/typography.scss
  projects/ontimize-web-ngx/src/lib/components/material/styles/variables.scss
  projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-column-resizer/o-table-column-resizer.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.component.html
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.component.ts
  projects/ontimize-web-ngx/src/lib/interfaces/app-menu.interface.ts
  projects/ontimize-web-ngx/src/lib/layouts/card-menu-layout/o-card-menu-layout.component.ts
  projects/ontimize-web-ngx/src/lib/services/ontimize-export-data-base-provider.service.ts
  projects/ontimize-web-ngx/src/lib/theming/ontimize-style.scss
Labels: release
