Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2024-05, with the labels that each got.

#1586 [8.14.14] [o-combo] Fixed bug with selected values
  projects/ontimize-web-ngx/src/lib/components/input/combo/combo-search/o-combo-search.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.html
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.ts
Labels: bug

#1587 [8.14.14] Changelog
  CHANGELOG.md
Labels: enhancement

#1585 Hotfix 8.14.14
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/input/combo/combo-search/o-combo-search.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.html
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.ts
Labels: release

#1589 Sync 8.14.14 to 15.x.x
  CHANGELOG.md
  projects/ontimize-web-ngx/src/lib/components/input/combo/combo-search/o-combo-search.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.html
  projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.ts
Labels: enhancement
