Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2024-01, with the labels that each got.

#1425 Hotfix 8.14.6
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts
  projects/ontimize-web-ngx/src/lib/i18n/i18n.ts
Labels: release

#1435 [15.x.x] Added new emitters in o-form
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
Labels: enhancement

#1437 [8.x.x] Added new emitters in o-form
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
Labels: enhancement

#1436 [15.x.x] Modified currency icons
  projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.html
  projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.scss
  projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.ts
Labels: bug

#1438 Release 15.0.0-beta.5
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
  projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/combo/combo-search/o-combo-search.component.html
  projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.html
  projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.scss
  projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/file-input/o-file-input.component.ts
  projects/ontimize-web-ngx/src/lib/components/input/o-form-service-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/cell-renderer/service/o-table-cell-renderer-service.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/components/theming/app-global.theme.scss
  projects/ontimize-web-ngx/src/lib/directives/o-mat-error.directive.ts
  projects/ontimize-web-ngx/src/lib/i18n/i18n.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager-base.class.ts
  projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/o-form-field-style.scss
Labels: release

#1441 [15.x.x] Solved bug with permissionsService
  projects/ontimize-web-ngx/src/lib/services/permissions/o-permissions.module.ts
  projects/ontimize-web-ngx/src/lib/services/permissions/permissions.service.ts
Labels: bug

#1456 Release 15.0.0-rc.0
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts
  projects/ontimize-web-ngx/src/lib/components/image/o-image.component.html
  projects/ontimize-web-ngx/src/lib/components/index.ts
  projects/ontimize-web-ngx/src/lib/components/tree/header/index.ts
  projects/ontimize-web-ngx/src/lib/components/tree/header/tree-menu/o-tree-menu.component.html
  projects/ontimize-web-ngx/src/lib/components/tree/header/tree-menu/o-tree-menu.component.ts
  projects/ontimize-web-ngx/src/lib/components/tree/index.ts
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree-dao.service.ts
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.component.html
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.component.scss
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.component.ts
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.datasource.ts
  projects/ontimize-web-ngx/src/lib/components/tree/o-tree.module.ts
  projects/ontimize-web-ngx/src/lib/components/tree/tree-node/tree-node.component.spec.ts
  projects/ontimize-web-ngx/src/lib/components/tree/tree-node/tree-node.component.ts
  projects/ontimize-web-ngx/src/lib/config/o-modules.ts
  projects/ontimize-web-ngx/src/lib/i18n/i18n.ts
  projects/ontimize-web-ngx/src/lib/services/permissions/o-permissions.module.ts
  projects/ontimize-web-ngx/src/lib/services/permissions/permissions.service.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-tree-component-state.class.ts
  projects/ontimize-web-ngx/src/lib/services/state/o-tree-component-state.service.ts
  projects/ontimize-web-ngx/src/lib/theming/ontimize-style-v8.scss
  projects/ontimize-web-ngx/src/lib/theming/styles/density.scss
  projects/ontimize-web-ngx/src/lib/theming/themes/ontimize-black-yellow.scss
Labels: release
