Repository OntimizeWeb/ontimize-web-ngx, pull requests merged in 2024-12, with the labels that each got.

#1775 [15.3.3] Fixed bug with permissionService
  projects/ontimize-web-ngx/src/lib/services/permissions/ontimize-ee-permissions.service.ts
Labels: bug

#1776 [15.3.3] Updated index
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/index.ts
  projects/ontimize-web-ngx/src/lib/components/bar-menu/index.ts
  projects/ontimize-web-ngx/src/lib/components/filter-builder/index.ts
  projects/ontimize-web-ngx/src/lib/components/form/index.ts
  projects/ontimize-web-ngx/src/lib/components/index.ts
  projects/ontimize-web-ngx/src/lib/layouts/index.ts
  projects/ontimize-web-ngx/src/lib/shared/index.ts
Labels: enhancement

#1765 Hotfix 15.3.3
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/app-sidenav/index.ts
  projects/ontimize-web-ngx/src/lib/components/bar-menu/index.ts
  projects/ontimize-web-ngx/src/lib/components/filter-builder/index.ts
  projects/ontimize-web-ngx/src/lib/components/form/index.ts
  projects/ontimize-web-ngx/src/lib/components/index.ts
  projects/ontimize-web-ngx/src/lib/components/input/radio/o-radio.component.ts
  projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/o-column.class.ts
  projects/ontimize-web-ngx/src/lib/components/table/column/o-table-column.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/export/o-table-export-dialog.component.scss
  projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-columns-filter/o-table-columns-filter.component.ts
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
  projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager-base.class.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
  projects/ontimize-web-ngx/src/lib/layouts/index.ts
  projects/ontimize-web-ngx/src/lib/services/navigation.service.ts
  projects/ontimize-web-ngx/src/lib/services/permissions/ontimize-ee-permissions.service.ts
  projects/ontimize-web-ngx/src/lib/shared/index.ts
  projects/ontimize-web-ngx/src/lib/types/form-layout-detail-component-data.type.ts
Labels: release

#1784 Hotfix 15.3.4
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx/package.json
  projects/ontimize-web-ngx/src/lib/components/input/input-theme.scss
  projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.html
  projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.ts
Labels: release
